name: page_builder_poc
description: Proof of concept for a low-code Flutter app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dio: ^5.3.3
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
